version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_DB: dataformatvalidator
    ports:
        - 5432:5432

  web:
    build: ./src/server/
    environment: 
      ASPNETCORE_URLS: "http://*:5000"
    ports:
      - 5000:5000