version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_DB: dataformatvalidator
    restart: always

  web:
    build: ./src/server/
    environment: 
      ASPNETCORE_URLS: "http://*:5000"
    ports:
      - 5000:5000
    depends_on: 
      - db
    restart: always

  frontend:
    build: ./src/frontend/
    ports:
      - 8080:80
    depends_on: 
      - web
    restart: always

  redis:
    image: 'bitnami/redis'
    environment:
      REDIS_PASSWORD: mystrongpassword
    restart: always